### ISSUE TITLE
Delete a user

### ISSUE THREAD

**Issue by machria** [qlik-oss/qlik-cli#16]
Hello,

I would like to get an example of how to run this command : 
qlik license assignment delete --delete
What look like the string needed ?

Best Regards,
Majid

**Comment by glooms** [comment]
Hi @machria, sorry for the late reply!

There was some issues with this command previously but it should now be at least possible, albeit still hard, to write the delete string.
Since `--delete` corresponds to an array of objects it's quite tricky to map it to command-line flags... so we don't at the moment. Instead, you have to write the JSON-array yourself. This can be hard, specifically in this case where there isn't much to go on but you can use
```
qlik license assignment ls
```
as a reference for what the `--delete` flag can contain. A correct invocation would look like these:
```
qlik license assignment delete --delete='[{"subject": "123","type": "professional"}]'
qlik license assignment delete --delete='[{"subject": "456","type": "professional"},{"subject": "789","type": "professional"}]'
```

Note that some terminals handle quotation marks differently and you might need to write the body with escaped double-quotation marks instead, like so: `"[{\"subject\":\"123\",\"type\":\"professional\"}]"`

Let me know if it works out!
